import type { Metadata } from "next";
import {
  Inter,
  Amiri,
  Noto_Naskh_Arabic,
  Scheherazade_New,
} from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QuranSettingsProvider } from "@/context/QuranSettingsContext";
import { AudioProvider } from "@/context/AudioContext";
import { AudioPlayerBar } from "@/components/shared/AudioPlayerBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const amiri = Amiri({
  variable: "--font-amiri",
  subsets: ["arabic"],
  weight: ["400", "700"],
});

const notoNaskhArabic = Noto_Naskh_Arabic({
  variable: "--font-noto-naskh",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

const scheherazade = Scheherazade_New({
  variable: "--font-scheherazade",
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${amiri.variable} ${notoNaskhArabic.variable} ${scheherazade.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-inter)]">
        <TooltipProvider>
          <QuranSettingsProvider>
            <AudioProvider>{children}
              <AudioPlayerBar />
            </AudioProvider>
          </QuranSettingsProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
